using System.ComponentModel.Composition;
using XrmToolBox.Extensibility;
using XrmToolBox.Extensibility.Interfaces;

namespace UserTeamRoleInspector
{
    [Export(typeof(IXrmToolBoxPlugin))]
    [ExportMetadata("Name", "User/Team Role Inspector")]
    [ExportMetadata("Description", "Read-only inspector: pick a user, see every security role they effectively hold, direct or via team membership, with the owning business unit for each.")]
    [ExportMetadata("SmallImageBase64", "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAH5SURBVFhHxZYxSEJRFIYdGxsbGxtbgsagpbGxsbFJgoYaGlwiGiqIwKGhloiWghaHQCOkrCxDwggJRQSLELEoqdAT/8v7kPvr9T2114EP4T/33XvOufeeq8/nD8u/QoLXkOA1JHgNCS0YWorJ1M6dBEIZmd5NyehanMZ0BAkak1tJKX18SzOrfFVl4eiRvnEFCXX6509lO1awFyuUPyWUKloVOEy+SKZYsX3nmbIMBs5oDkeQUEctbspyInhrBQa7f3qXvrkTGtMWEvxha6/V4mMbN+RvBJVS1QhG8+Rviy4gC7XnrTLXwYFU5vpw6sLwyqU1EbLSfSbUls0epMlnRBdm9h+sifaun3mwgU6/owCwj27Kr1DbgMOo+4zoAkoIW4/keLABdXBxRXWfEV3A1YLhbus+EwgYtnycJZ8RXcC1Uub0ROMb1Q/QOXW/ERIasnHSXAYWo3KRfbWr1m48QUK9F2BxNSkeIn0MQObx3O/i1ZrIyOoVjWkLCXXQD1RZ0RFRFZQX24JzgjdB+Ws160cS+TcrKH0uIyQ0gMnwAJkMi45vJux27DoIEpqgMo6kS1bW+MVpx/8Cted4DTsKgoQu6CgIErrEdRAk9ABXQZDQIxwHQUIPcRQECT2mMQjcJN3/5wEABIFG1rSjkuA1JHgNCV5Dgsf8AFedgMPgeg70AAAAAElFTkSuQmCC")]
    [ExportMetadata("BigImageBase64", "iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAARWSURBVHhe7Zs/aBVBEMYtLS0tLS0tLS0tLS0trUSw0MIijYiNgk0KC21EbBRsLAQVCRrEfwSJSJCIBqJICEE0/kFOvgcXkvlm7t3cu5u9d9mBX/Ox9+52bnZ3dvbenj2nHhaZCSAh44OEjA8SMj5IyPggIeODhIwPEjI+SMj4ICHjg4QOOHhhvjh9Z6mYub9c3F34VjxaWt8BdHDo0nO6tveQ0BJw2sUHH4t3X34UHlvd+F3Mzq0UR2ff0G/2EhIm5MDM0+LWy6/SL40M0Xn48gu6R68goSF7zzwurjz6JH3QimHY7z8/R/fsBSQ0AFH3euW77HerhqHdy2gkwcmRq6+K9Z9/ZX/J4GDMiSduLo6uKTl2bWG0gGC4jrPNP/+Kk7ff0zMkhQQHcECVwbHn7n0YRai8VmPf2ScjBy+vbcqf2mFY0eW1ySChJnCKFXmIFEQVHCKvqwPmUzgJw9YyvDx5XRJIqAE6aKUniJ628jksHM+WN+QtRoaXVzeyO4WEGlirLTrbNOos8LKstAjzqmwfDgljQHRphshr23klcKIViViEZPtQSBgDcjJpmPOw85Bt2wTDWZsTocHBsn0YJFRgRV/Uqoho0yzq/iokVKDNfdERoA3lpHMhCRVo+Vn027dGQbKtHgkGfXpw7UUiAZftQiDBADsKadh+yXYRaFMJUh3ZLgQSDK7Pr8pnHjlVtosAtUJpmBtluxBIMLi/uCafOVkOhh2INAxr2S4EEgy0clWq8hJWfc1kuxBIMNCS2JR70d48DwkGWvGgraJBEzSLzEe3IMFAK3imOvhB6iQN1RnZLgQSDLRVOFV1WMtJk+1GSDBAOV5aqtxLy0mRJch2IZBgoOVeGDYp5h1tOkmVk9Z2IByFspW06FwQNUftOZItaCRUoFWGo+cenLVIS5ZEAxIqwIZds6goxOqrRR8WONk2DBIqsA6ToEXMhVY1PEkCXULCGKyqMDon27bBuLNiVGbkNaGQUANtXwzrojMo2FqG7VxXB1m1IaEGWPG0uQiGSGyzU5/Xf8lbbFnU3FsJCTWxhjIMc+KklRosGFoJrbSpPlgv0VKK7YZo9HYSixGSYuuzke2GedH7+61DghOtvC4N1WI4xYpKnCljXw2HW1ODZcmdSEIDjt946+64lg6NM+seSZ1IQkMQXVaqMalhOOMlYfGyhnYyJ5IwAeVnaVYnmximiO2reu+cSEILoMPoeNOIhIOw77a+t+mVE0lomfI/IkhJrHkPnUaJCjVHa6GR9MaJJASBL0wn3T/3wokkTBnJnUjCFJLUiSRMKcmcSMIUk8SJJEw54U4kYQCEOpGEgRDmRBIGRIgTSRgYnTuRhAHSqRNJGCidOZGEAdOJE0kYOFVObPSFAwm7AMuJODKQbcdCwi5Bc2Kj/72QsIuAE8vvbXByWLeYuwMSMj5IyPggIeODhIwPEjI+SMj4ICHjg4SMDxIyPkjI+CAh44OEjIv/sLtal07smSkAAAAASUVORK5CYII=")]
    [ExportMetadata("BackgroundColor", "White")]
    [ExportMetadata("PrimaryFontColor", "Black")]
    [ExportMetadata("SecondaryFontColor", "DarkGray")]
    public class UserTeamRoleInspectorPlugin : PluginBase
    {
        public override IXrmToolBoxPluginControl GetControl()
        {
            return new UserTeamRoleInspectorControl();
        }
    }
}
